---
title: "logo"
author: "Adrian Correndo"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LOGO

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(hexSticker)
library(metrica)
library(ggplot2)
library(usmap)
library(viridis)


p <- plot_usmap(exclude = c('AK','HI'), fill='#cc4c02', size=0.1)


scat <- ggplot(wheat, aes(pre, obs, fill = ..density..)) +
  ggplot2::coord_fixed(xlim = c(round(min(c(min(wheat$pre),
                                            min(wheat$obs)))),
                                round(max(c(max(wheat$pre),
                                            max(wheat$obs))))),
                       ylim = c(round(min(c(min(wheat$pre),
                                            min(wheat$obs)))),
                                round(max(c(max(wheat$pre), 
                                            max(wheat$obs))))))+
  geom_hex(bins = 6, color = "steelblue", size=0.15) +
  geom_abline(col ="#edeec9")+
  scale_fill_viridis(option = "viridis", direction = -1) +
  #scale_fill_distiller(palette = "YlOrRd", direction = 1) +
  labs(x = "", y = "")+
  #theme_void()+
  theme(legend.position = "none",
        panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "#edeec9"),
        axis.ticks.length = unit(.15, "line"),
        axis.ticks = element_line(colour = "#edeec9"),
        axis.text = element_blank(),
        aspect.ratio = 1)

scat

set.seed(1)

s <- sticker(scat,
             package="metrica", 
             p_size=28,p_color = "#edeec9",p_y = 0.6,
             s_x=0.925, s_y=1.15, 
             s_width=1.15, s_height=1.05,
             spotlight=T, l_height = 2.25, l_width = 2.25,
             l_x=.975,l_y=0.35,
             h_color = "#edeec9", h_fill = "#003049",h_size=0.2,
             filename="metrica_logo.png")

```


