#' @title import.apsim.out
#' @description Function to import *.out files generated by APSIM Classic.
#' @note it will create a data frame object, one file at a time.
#' @param filepath Argument to specify the location path to the *.out file.
#' @return Element of class `data.frame`.
#' @details This function will generate a data frame object from an APSIM Classic *.out file.
#' @examples 
#' \dontrun{
#' # Pull the git repo and use the following filepath
#' path <- "tests/testthat/examples/soybean.out"
#' soybean.out <- import.apsim.out(filepath = path)
#' head(soybean.out)
#' }
#' @rdname import.apsim.out
#' @importFrom utils read.delim
#' @export 

import.apsim.out <- function(filepath){
  uppersection <- utils::read.delim(filepath, sep = "",skip = 2,nrows = 1)
  
  COLNAMES <- colnames(uppersection)
  UNITY <- unlist(lapply(uppersection, as.character))
  HEADER <- mapply(function(x,y){paste(x,y)},COLNAMES,UNITY, SIMPLIFY = FALSE)
  
  
  dataframe <- utils::read.delim(filepath,sep = "",skip = 3,na.strings = c("?"),dec = ".")
  colnames(dataframe) <- HEADER
  
  return(dataframe)
}
